"""Use the official DNS engine and mihomo kernel as publication gates."""
from __future__ import annotations

import json
import os
from pathlib import Path
import re
import socket
import subprocess
import tempfile
import time
from urllib.request import ProxyHandler, build_opener

from .network import atomic, json_text

BUCKETS = ("block", "allow", "block-important", "allow-important")


def dns_binary() -> str:
    fallback = Path(".cache/dns-rule-validator" + (".exe" if os.name == "nt" else ""))
    return os.environ.get("DNS_RULE_VALIDATOR", str(fallback.resolve()))


def validate_dns(rules: list[str]) -> dict:
    result = subprocess.run([dns_binary()], input="\n".join(rules) + "\n", text=True,
                            encoding="utf-8", capture_output=True, timeout=90)
    report = json.loads(result.stdout)
    if result.returncode or report.get("invalid") or report.get("checked") != len(rules):
        raise ValueError("AdGuard DNS engine rejected output: " + json_text(report))
    return report


def match_dns(cases: list[dict]) -> list[list[bool]]:
    result = subprocess.run([dns_binary(), "-match"], input=json.dumps(cases), text=True,
                            encoding="utf-8", capture_output=True, timeout=90)
    if result.returncode:
        raise ValueError("AdGuard match failed: " + result.stderr[:400])
    return json.loads(result.stdout)


def mihomo_rule(line: str) -> tuple[str, str, str]:
    bucket = ("allow" if line.startswith("@@") else "block") + ("-important" if line.endswith("$important") else "")
    pattern = line.removeprefix("@@").removesuffix("$important")
    simple = re.fullmatch(r"(\|\||\|)([a-z0-9_.-]+)(\^|\|)", pattern)
    if simple:
        return bucket, "domain", ("+." if simple[1] == "||" else "") + simple[2]
    if pattern.startswith("/") and pattern.endswith("/"):
        expression = pattern[1:-1]
    else:
        start = ""
        if pattern.startswith("||"):
            start, pattern = r"^(?:[a-z0-9_.-]+\.)?", pattern[2:]
        elif pattern.startswith("|"):
            start, pattern = "^", pattern[1:]
        end = "$" if pattern.endswith("|") else ""
        if end:
            pattern = pattern[:-1]
        expression = start + "".join(".*" if c == "*" else r"(?:[^ a-zA-Z0-9.%_-]|$)" if c == "^" else re.escape(c)
                                      for c in pattern) + end
    # Both engines match DNS case-insensitively; never turn a regex into a suffix.
    return bucket, "classical", "DOMAIN-REGEX,(?i)" + expression


def rejection_rules(prefix: str) -> list[str]:
    def group(bucket: str) -> str:
        return f"(OR,((RULE-SET,{prefix}-{bucket}-domain),(RULE-SET,{prefix}-{bucket}-classical)))"
    result = []
    for bucket in ("block-important", "block"):
        exceptions = ("allow-important",) if bucket == "block-important" else ("allow-important", "allow")
        terms = [group(bucket)] + [f"(NOT,({group(e)}))" for e in exceptions]
        result.append("AND,(" + ",".join(terms) + "),REJECT")
    return result


def export_mihomo(directory: Path, pid: str, rules: list[str], repository: str, notices: list[str] | None = None) -> dict:
    payloads = {(b, kind): [] for b in BUCKETS for kind in ("domain", "classical")}
    for line in rules:
        bucket, kind, value = mihomo_rule(line)
        payloads[bucket, kind].append(value)
    providers, files = {}, []
    for (bucket, kind), values in payloads.items():
        name = f"{pid}-{bucket}-{kind}"
        filename = name + ".txt"
        comments = ["# Generated by the Excel source compiler; original upstream authors retain credit."]
        comments += ["#" + n[1:] for n in (notices or []) if n.startswith("!")]
        atomic(directory / filename, "\n".join(comments + sorted(set(values))) + "\n")
        providers[name] = {"type": "http", "behavior": kind, "format": "text", "interval": 86400,
                           "url": f"https://raw.githubusercontent.com/{repository}/main/dist/mihomo/{filename}",
                           "path": "./rule_provider/excel/" + filename}
        files.append(filename)
    routing = rejection_rules(pid)
    for label, accelerator in (("", ""), ("-boki", "https://github.boki.moe/"), ("-ghfast", "https://ghfast.top/")):
        config = {"rule-providers": {name: dict(provider, url=accelerator + provider["url"])
                                      for name, provider in providers.items()}, "rules": routing}
        filename = pid + label + ".yaml"
        atomic(directory / filename, json_text(config))
        files.append(filename)
    verify_mihomo(directory, pid, payloads, routing)
    return {"files": files, "domain": sum(len(v) for (b, k), v in payloads.items() if k == "domain"),
            "classical": sum(len(v) for (b, k), v in payloads.items() if k == "classical")}


def verify_mihomo(directory: Path, pid: str, payloads: dict, routing: list[str]) -> None:
    binary = os.environ.get("MIHOMO_BINARY", str(Path(".cache/mihomo/mihomo" + (".exe" if os.name == "nt" else "")).resolve()))
    version = subprocess.run([binary, "-v"], capture_output=True, text=True, encoding="utf-8", timeout=15)
    if version.returncode or "v1.19.32" not in version.stdout:
        raise ValueError("Expected checksum-pinned official mihomo v1.19.32")
    with socket.socket() as port:
        port.bind(("127.0.0.1", 0))
        number = port.getsockname()[1]
    with tempfile.TemporaryDirectory(prefix="mihomo-check-", dir=directory) as tmp:
        folder = Path(tmp)
        expected = {f"{pid}-{b}-{k}": len(set(values)) for (b, k), values in payloads.items()}
        for name in expected:
            atomic(folder / (name + ".txt"), (directory / (name + ".txt")).read_bytes())
        config = {"port": 0, "socks-port": 0, "mixed-port": 0, "allow-lan": False, "log-level": "info",
                  "external-controller": f"127.0.0.1:{number}", "dns": {"enable": False},
                  "rule-providers": {name: {"type": "file", "behavior": k, "format": "text",
                                            "path": name + ".txt"}
                                     for (b, k), values in payloads.items() for name in [f"{pid}-{b}-{k}"]},
                  "rules": routing + ["MATCH,DIRECT"]}
        path = folder / "config.yaml"
        atomic(path, json_text(config))
        logs = folder / "kernel.log"
        with logs.open("wb") as stream:
            process = subprocess.Popen([binary, "-d", str(folder.resolve()), "-f", str(path.resolve())], stdout=stream, stderr=stream)
            try:
                opener = build_opener(ProxyHandler({}))
                deadline = time.monotonic() + 20
                last_error = "kernel did not start"
                while time.monotonic() < deadline:
                    if process.poll() is not None:
                        break
                    try:
                        with opener.open(f"http://127.0.0.1:{number}/providers/rules", timeout=1) as response:
                            loaded = json.load(response).get("providers") or {}
                        if set(loaded) == set(expected) and all(loaded[n]["ruleCount"] == c for n, c in expected.items()):
                            return
                        last_error = f"Provider counts differ: {[(n, loaded.get(n, {}).get('ruleCount'), c) for n, c in expected.items()]}"
                    except Exception as error:
                        last_error = str(error)
                    time.sleep(.1)
                raise ValueError(last_error + ": " + logs.read_text(encoding="utf-8", errors="replace")[-1500:])
            finally:
                if process.poll() is None:
                    process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
